using DobriyCoder.Core.Common;

namespace CryptoCoinAPI
{

    public class CoingeckoCoinData
    {
        IErrors? Errors { get; set; }
        public string? id { get; set; }
        public string? symbol { get; set; }
        public string? name { get; set; }
        public object? asset_platform_id { get; set; }
        public Dictionary<string, object>? platforms { get; set; }
        public Dictionary<string, object>? detail_platforms { get; set; }
        public double? block_time_in_minutes { get; set; }
        public string? hashing_algorithm { get; set; }
        public string[]? categories { get; set; }
        public object? public_notice { get; set; }
        public object[]? additional_notices { get; set; }
        public Dictionary<string, object>? localization { get; set; }
        public Dictionary<string, object>? description { get; set; }
        public Dictionary<string, object>? links { get; set; }
        public Dictionary<string, object>? image { get; set; }
        public string? country_origin { get; set; }
        public string? genesis_date { get; set; }
        public double? sentiment_votes_up_percentage { get; set; }
        public double? sentiment_votes_down_percentage { get; set; }
        public double? market_cap_rank { get; set; }
        public double? coingecko_rank { get; set; }
        public double? coingecko_score { get; set; }
        public double? developer_score { get; set; }
        public double? community_score { get; set; }
        public double? liquidity_score { get; set; }
        public double? public_doubleerest_score { get; set; }
        public Market_Data? market_data { get; set; }
        public Dictionary<string, object>? community_data { get; set; }
        public Dictionary<string, object>? developer_data { get; set; }
        public Dictionary<string, object>? public_doubleerest_stats { get; set; }
        public object[]? status_updates { get; set; }
        public DateTime last_updated { get; set; }
        public Ticker[]? tickers { get; set; }
    }

    public class Child
    {
        public object? decimal_place { get; set; }
        public string? contract_address { get; set; }
    }

    public class Market_Data
    {
        public Current_Price? current_price { get; set; }
        public object? total_value_locked { get; set; }
        public object? mcap_to_tvl_ratio { get; set; }
        public object? fdv_to_tvl_ratio { get; set; }
        public object? roi { get; set; }
        public Ath? ath { get; set; }
        public Ath_Change_Percentage? ath_change_percentage { get; set; }
        public Ath_Date? ath_date { get; set; }
        public Atl? atl { get; set; }
        public Atl_Change_Percentage? atl_change_percentage { get; set; }
        public Atl_Date? atl_date { get; set; }
        public Market_Cap? market_cap { get; set; }
        public double? market_cap_rank { get; set; }
        public Fully_Diluted_Valuation? fully_diluted_valuation { get; set; }
        public Total_Volume? total_volume { get; set; }
        public High_24H? high_24h { get; set; }
        public Low_24H? low_24h { get; set; }
        public double? price_change_24h { get; set; }
        public double? price_change_percentage_24h { get; set; }
        public double? price_change_percentage_7d { get; set; }
        public double? price_change_percentage_14d { get; set; }
        public double? price_change_percentage_30d { get; set; }
        public double? price_change_percentage_60d { get; set; }
        public double? price_change_percentage_200d { get; set; }
        public double? price_change_percentage_1y { get; set; }
        public double? market_cap_change_24h { get; set; }
        public double? market_cap_change_percentage_24h { get; set; }
        public Price_Change_24H_In_Currency? price_change_24h_in_currency { get; set; }
        public Price_Change_Percentage_1H_In_Currency? price_change_percentage_1h_in_currency { get; set; }
        public Price_Change_Percentage_24H_In_Currency? price_change_percentage_24h_in_currency { get; set; }
        public Price_Change_Percentage_7D_In_Currency? price_change_percentage_7d_in_currency { get; set; }
        public Price_Change_Percentage_14D_In_Currency? price_change_percentage_14d_in_currency { get; set; }
        public Price_Change_Percentage_30D_In_Currency? price_change_percentage_30d_in_currency { get; set; }
        public Price_Change_Percentage_60D_In_Currency? price_change_percentage_60d_in_currency { get; set; }
        public Price_Change_Percentage_200D_In_Currency? price_change_percentage_200d_in_currency { get; set; }
        public Price_Change_Percentage_1Y_In_Currency? price_change_percentage_1y_in_currency { get; set; }
        public Market_Cap_Change_24H_In_Currency? market_cap_change_24h_in_currency { get; set; }
        public Market_Cap_Change_Percentage_24H_In_Currency? market_cap_change_percentage_24h_in_currency { get; set; }
        public double? total_supply { get; set; }
        public double? max_supply { get; set; }
        public double? circulating_supply { get; set; }
        public DateTime last_updated { get; set; }
    }

    public class Current_Price
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Ath
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Ath_Change_Percentage
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Ath_Date
    {
        public DateTime aed { get; set; }
        public DateTime ars { get; set; }
        public DateTime aud { get; set; }
        public DateTime bch { get; set; }
        public DateTime bdt { get; set; }
        public DateTime bhd { get; set; }
        public DateTime bmd { get; set; }
        public DateTime bnb { get; set; }
        public DateTime brl { get; set; }
        public DateTime btc { get; set; }
        public DateTime cad { get; set; }
        public DateTime chf { get; set; }
        public DateTime clp { get; set; }
        public DateTime cny { get; set; }
        public DateTime czk { get; set; }
        public DateTime dkk { get; set; }
        public DateTime dot { get; set; }
        public DateTime eos { get; set; }
        public DateTime eth { get; set; }
        public DateTime eur { get; set; }
        public DateTime gbp { get; set; }
        public DateTime hkd { get; set; }
        public DateTime huf { get; set; }
        public DateTime idr { get; set; }
        public DateTime ils { get; set; }
        public DateTime inr { get; set; }
        public DateTime jpy { get; set; }
        public DateTime krw { get; set; }
        public DateTime kwd { get; set; }
        public DateTime lkr { get; set; }
        public DateTime ltc { get; set; }
        public DateTime mmk { get; set; }
        public DateTime mxn { get; set; }
        public DateTime myr { get; set; }
        public DateTime ngn { get; set; }
        public DateTime nok { get; set; }
        public DateTime nzd { get; set; }
        public DateTime php { get; set; }
        public DateTime pkr { get; set; }
        public DateTime pln { get; set; }
        public DateTime rub { get; set; }
        public DateTime sar { get; set; }
        public DateTime sek { get; set; }
        public DateTime sgd { get; set; }
        public DateTime thb { get; set; }
        public DateTime _try { get; set; }
        public DateTime twd { get; set; }
        public DateTime uah { get; set; }
        public DateTime usd { get; set; }
        public DateTime vef { get; set; }
        public DateTime vnd { get; set; }
        public DateTime xag { get; set; }
        public DateTime xau { get; set; }
        public DateTime xdr { get; set; }
        public DateTime xlm { get; set; }
        public DateTime xrp { get; set; }
        public DateTime yfi { get; set; }
        public DateTime zar { get; set; }
        public DateTime bits { get; set; }
        public DateTime link { get; set; }
        public DateTime sats { get; set; }
    }

    public class Atl
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Atl_Change_Percentage
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Atl_Date
    {
        public DateTime aed { get; set; }
        public DateTime ars { get; set; }
        public DateTime aud { get; set; }
        public DateTime bch { get; set; }
        public DateTime bdt { get; set; }
        public DateTime bhd { get; set; }
        public DateTime bmd { get; set; }
        public DateTime bnb { get; set; }
        public DateTime brl { get; set; }
        public DateTime btc { get; set; }
        public DateTime cad { get; set; }
        public DateTime chf { get; set; }
        public DateTime clp { get; set; }
        public DateTime cny { get; set; }
        public DateTime czk { get; set; }
        public DateTime dkk { get; set; }
        public DateTime dot { get; set; }
        public DateTime eos { get; set; }
        public DateTime eth { get; set; }
        public DateTime eur { get; set; }
        public DateTime gbp { get; set; }
        public DateTime hkd { get; set; }
        public DateTime huf { get; set; }
        public DateTime idr { get; set; }
        public DateTime ils { get; set; }
        public DateTime inr { get; set; }
        public DateTime jpy { get; set; }
        public DateTime krw { get; set; }
        public DateTime kwd { get; set; }
        public DateTime lkr { get; set; }
        public DateTime ltc { get; set; }
        public DateTime mmk { get; set; }
        public DateTime mxn { get; set; }
        public DateTime myr { get; set; }
        public DateTime ngn { get; set; }
        public DateTime nok { get; set; }
        public DateTime nzd { get; set; }
        public DateTime php { get; set; }
        public DateTime pkr { get; set; }
        public DateTime pln { get; set; }
        public DateTime rub { get; set; }
        public DateTime sar { get; set; }
        public DateTime sek { get; set; }
        public DateTime sgd { get; set; }
        public DateTime thb { get; set; }
        public DateTime _try { get; set; }
        public DateTime twd { get; set; }
        public DateTime uah { get; set; }
        public DateTime usd { get; set; }
        public DateTime vef { get; set; }
        public DateTime vnd { get; set; }
        public DateTime xag { get; set; }
        public DateTime xau { get; set; }
        public DateTime xdr { get; set; }
        public DateTime xlm { get; set; }
        public DateTime xrp { get; set; }
        public DateTime yfi { get; set; }
        public DateTime zar { get; set; }
        public DateTime bits { get; set; }
        public DateTime link { get; set; }
        public DateTime sats { get; set; }
    }

    public class Market_Cap
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Fully_Diluted_Valuation
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Total_Volume
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class High_24H
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Low_24H
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Price_Change_24H_In_Currency
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Price_Change_Percentage_1H_In_Currency
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Price_Change_Percentage_24H_In_Currency
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Price_Change_Percentage_7D_In_Currency
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Price_Change_Percentage_14D_In_Currency
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Price_Change_Percentage_30D_In_Currency
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Price_Change_Percentage_60D_In_Currency
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Price_Change_Percentage_200D_In_Currency
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Price_Change_Percentage_1Y_In_Currency
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Market_Cap_Change_24H_In_Currency
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Market_Cap_Change_Percentage_24H_In_Currency
    {
        public double? aed { get; set; }
        public double? ars { get; set; }
        public double? aud { get; set; }
        public double? bch { get; set; }
        public double? bdt { get; set; }
        public double? bhd { get; set; }
        public double? bmd { get; set; }
        public double? bnb { get; set; }
        public double? brl { get; set; }
        public double? btc { get; set; }
        public double? cad { get; set; }
        public double? chf { get; set; }
        public double? clp { get; set; }
        public double? cny { get; set; }
        public double? czk { get; set; }
        public double? dkk { get; set; }
        public double? dot { get; set; }
        public double? eos { get; set; }
        public double? eth { get; set; }
        public double? eur { get; set; }
        public double? gbp { get; set; }
        public double? hkd { get; set; }
        public double? huf { get; set; }
        public double? idr { get; set; }
        public double? ils { get; set; }
        public double? inr { get; set; }
        public double? jpy { get; set; }
        public double? krw { get; set; }
        public double? kwd { get; set; }
        public double? lkr { get; set; }
        public double? ltc { get; set; }
        public double? mmk { get; set; }
        public double? mxn { get; set; }
        public double? myr { get; set; }
        public double? ngn { get; set; }
        public double? nok { get; set; }
        public double? nzd { get; set; }
        public double? php { get; set; }
        public double? pkr { get; set; }
        public double? pln { get; set; }
        public double? rub { get; set; }
        public double? sar { get; set; }
        public double? sek { get; set; }
        public double? sgd { get; set; }
        public double? thb { get; set; }
        public double? _try { get; set; }
        public double? twd { get; set; }
        public double? uah { get; set; }
        public double? usd { get; set; }
        public double? vef { get; set; }
        public double? vnd { get; set; }
        public double? xag { get; set; }
        public double? xau { get; set; }
        public double? xdr { get; set; }
        public double? xlm { get; set; }
        public double? xrp { get; set; }
        public double? yfi { get; set; }
        public double? zar { get; set; }
        public double? bits { get; set; }
        public double? link { get; set; }
        public double? sats { get; set; }
    }

    public class Community_Data
    {
        public object? facebook_likes { get; set; }
        public double? twitter_followers { get; set; }
        public double? reddit_average_posts_48h { get; set; }
        public double? reddit_average_comments_48h { get; set; }
        public double? reddit_subscribers { get; set; }
        public double? reddit_accounts_active_48h { get; set; }
        public object? telegram_channel_user_count { get; set; }
    }

    public class Developer_Data
    {
        public double? forks { get; set; }
        public double? stars { get; set; }
        public double? subscribers { get; set; }
        public double? total_issues { get; set; }
        public double? closed_issues { get; set; }
        public double? pull_requests_merged { get; set; }
        public double? pull_request_contributors { get; set; }
        public Code_Additions_Deletions_4_Weeks? code_additions_deletions_4_weeks { get; set; }
        public double? commit_count_4_weeks { get; set; }
        public double[]? last_4_weeks_commit_activity_series { get; set; }
    }

    public class Code_Additions_Deletions_4_Weeks
    {
        public double? additions { get; set; }
        public double? deletions { get; set; }
    }

    public class Public_doubleerest_Stats
    {
        public double? alexa_rank { get; set; }
        public object? bing_matches { get; set; }
    }

    public class Ticker
    {
        public string? _base { get; set; }
        public string? target { get; set; }
        public Market? market { get; set; }
        public double? last { get; set; }
        public double? volume { get; set; }
        public Converted_Last? converted_last { get; set; }
        public Converted_Volume? converted_volume { get; set; }
        public string? trust_score { get; set; }
        public double? bid_ask_spread_percentage { get; set; }
        public DateTime timestamp { get; set; }
        public DateTime last_traded_at { get; set; }
        public DateTime last_fetch_at { get; set; }
        public bool is_anomaly { get; set; }
        public bool is_stale { get; set; }
        public string? trade_url { get; set; }
        public object? token_info_url { get; set; }
        public string? coin_id { get; set; }
        public string? target_coin_id { get; set; }
    }

    public class Market
    {
        public string? name { get; set; }
        public string? identifier { get; set; }
        public bool has_trading_incentive { get; set; }
    }

    public class Converted_Last
    {
        public double? btc { get; set; }
        public double? eth { get; set; }
        public double? usd { get; set; }
    }

    public class Converted_Volume
    {
        public double? btc { get; set; }
        public double? eth { get; set; }
        public double? usd { get; set; }
    }

}
