namespace CryptoCoinAPI
{
    public class CoingeckoCoinData
    {
        public string id { get; set; }
        public string symbol { get; set; }
        public string name { get; set; }
        public object asset_platform_id { get; set; }
        public Platforms platforms { get; set; }
        public Detail_Platforms detail_platforms { get; set; }
        public string block_time_in_minutes { get; set; }
        public string hashing_algorithm { get; set; }
        public string[] categories { get; set; }
        public object public_notice { get; set; }
        public object[] additional_notices { get; set; }
        public Localization localization { get; set; }
        public Description description { get; set; }
        public Links links { get; set; }
        public Image image { get; set; }
        public string country_origin { get; set; }
        public string genesis_date { get; set; }
        public string sentiment_votes_up_percentage { get; set; }
        public string sentiment_votes_down_percentage { get; set; }
        public string market_cap_rank { get; set; }
        public string coingecko_rank { get; set; }
        public string coingecko_score { get; set; }
        public string developer_score { get; set; }
        public string community_score { get; set; }
        public string liquidity_score { get; set; }
        public string public_stringerest_score { get; set; }
        public Market_Data market_data { get; set; }
        public Community_Data community_data { get; set; }
        public Developer_Data developer_data { get; set; }
        public Public_stringerest_Stats public_stringerest_stats { get; set; }
        public object[] status_updates { get; set; }
        public DateTime last_updated { get; set; }
        public Ticker[] tickers { get; set; }
    }

    public class Platforms
    {
        public string _ { get; set; }
    }

    public class Detail_Platforms
    {
        public Child _ { get; set; }
    }

    public class Child
    {
        public object string_place { get; set; }
        public string contract_address { get; set; }
    }

    public class Localization
    {
        public string en { get; set; }
        public string de { get; set; }
        public string es { get; set; }
        public string fr { get; set; }
        public string it { get; set; }
        public string pl { get; set; }
        public string ro { get; set; }
        public string hu { get; set; }
        public string nl { get; set; }
        public string pt { get; set; }
        public string sv { get; set; }
        public string vi { get; set; }
        public string tr { get; set; }
        public string ru { get; set; }
        public string ja { get; set; }
        public string zh { get; set; }
        public string zhtw { get; set; }
        public string ko { get; set; }
        public string ar { get; set; }
        public string th { get; set; }
        public string id { get; set; }
        public string cs { get; set; }
        public string da { get; set; }
        public string el { get; set; }
        public string hi { get; set; }
        public string no { get; set; }
        public string sk { get; set; }
        public string uk { get; set; }
        public string he { get; set; }
        public string fi { get; set; }
        public string bg { get; set; }
        public string hr { get; set; }
        public string lt { get; set; }
        public string sl { get; set; }
    }

    public class Description
    {
        public string en { get; set; }
        public string de { get; set; }
        public string es { get; set; }
        public string fr { get; set; }
        public string it { get; set; }
        public string pl { get; set; }
        public string ro { get; set; }
        public string hu { get; set; }
        public string nl { get; set; }
        public string pt { get; set; }
        public string sv { get; set; }
        public string vi { get; set; }
        public string tr { get; set; }
        public string ru { get; set; }
        public string ja { get; set; }
        public string zh { get; set; }
        public string zhtw { get; set; }
        public string ko { get; set; }
        public string ar { get; set; }
        public string th { get; set; }
        public string id { get; set; }
        public string cs { get; set; }
        public string da { get; set; }
        public string el { get; set; }
        public string hi { get; set; }
        public string no { get; set; }
        public string sk { get; set; }
        public string uk { get; set; }
        public string he { get; set; }
        public string fi { get; set; }
        public string bg { get; set; }
        public string hr { get; set; }
        public string lt { get; set; }
        public string sl { get; set; }
    }

    public class Links
    {
        public string[] homepage { get; set; }
        public string[] blockchain_site { get; set; }
        public string[] official_forum_url { get; set; }
        public string[] chat_url { get; set; }
        public string[] announcement_url { get; set; }
        public string twitter_screen_name { get; set; }
        public string facebook_username { get; set; }
        public object bitcostringalk_thread_identifier { get; set; }
        public string telegram_channel_identifier { get; set; }
        public string subreddit_url { get; set; }
        public Repos_Url repos_url { get; set; }
    }

    public class Repos_Url
    {
        public string[] github { get; set; }
        public object[] bitbucket { get; set; }
    }

    public class Image
    {
        public string thumb { get; set; }
        public string small { get; set; }
        public string large { get; set; }
    }

    public class Market_Data
    {
        public Current_Price current_price { get; set; }
        public object total_value_locked { get; set; }
        public object mcap_to_tvl_ratio { get; set; }
        public object fdv_to_tvl_ratio { get; set; }
        public object roi { get; set; }
        public Ath ath { get; set; }
        public Ath_Change_Percentage ath_change_percentage { get; set; }
        public Ath_Date ath_date { get; set; }
        public Atl atl { get; set; }
        public Atl_Change_Percentage atl_change_percentage { get; set; }
        public Atl_Date atl_date { get; set; }
        public Market_Cap market_cap { get; set; }
        public string market_cap_rank { get; set; }
        public Fully_Diluted_Valuation fully_diluted_valuation { get; set; }
        public Total_Volume total_volume { get; set; }
        public High_24H high_24h { get; set; }
        public Low_24H low_24h { get; set; }
        public string price_change_24h { get; set; }
        public string price_change_percentage_24h { get; set; }
        public string price_change_percentage_7d { get; set; }
        public string price_change_percentage_14d { get; set; }
        public string price_change_percentage_30d { get; set; }
        public string price_change_percentage_60d { get; set; }
        public string price_change_percentage_200d { get; set; }
        public string price_change_percentage_1y { get; set; }
        public string market_cap_change_24h { get; set; }
        public string market_cap_change_percentage_24h { get; set; }
        public Price_Change_24H_In_Currency price_change_24h_in_currency { get; set; }
        public Price_Change_Percentage_1H_In_Currency price_change_percentage_1h_in_currency { get; set; }
        public Price_Change_Percentage_24H_In_Currency price_change_percentage_24h_in_currency { get; set; }
        public Price_Change_Percentage_7D_In_Currency price_change_percentage_7d_in_currency { get; set; }
        public Price_Change_Percentage_14D_In_Currency price_change_percentage_14d_in_currency { get; set; }
        public Price_Change_Percentage_30D_In_Currency price_change_percentage_30d_in_currency { get; set; }
        public Price_Change_Percentage_60D_In_Currency price_change_percentage_60d_in_currency { get; set; }
        public Price_Change_Percentage_200D_In_Currency price_change_percentage_200d_in_currency { get; set; }
        public Price_Change_Percentage_1Y_In_Currency price_change_percentage_1y_in_currency { get; set; }
        public Market_Cap_Change_24H_In_Currency market_cap_change_24h_in_currency { get; set; }
        public Market_Cap_Change_Percentage_24H_In_Currency market_cap_change_percentage_24h_in_currency { get; set; }
        public string total_supply { get; set; }
        public string max_supply { get; set; }
        public string circulating_supply { get; set; }
        public DateTime last_updated { get; set; }
    }

    public class Current_Price
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Ath
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Ath_Change_Percentage
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Ath_Date
    {
        public DateTime aed { get; set; }
        public DateTime ars { get; set; }
        public DateTime aud { get; set; }
        public DateTime bch { get; set; }
        public DateTime bdt { get; set; }
        public DateTime bhd { get; set; }
        public DateTime bmd { get; set; }
        public DateTime bnb { get; set; }
        public DateTime brl { get; set; }
        public DateTime btc { get; set; }
        public DateTime cad { get; set; }
        public DateTime chf { get; set; }
        public DateTime clp { get; set; }
        public DateTime cny { get; set; }
        public DateTime czk { get; set; }
        public DateTime dkk { get; set; }
        public DateTime dot { get; set; }
        public DateTime eos { get; set; }
        public DateTime eth { get; set; }
        public DateTime eur { get; set; }
        public DateTime gbp { get; set; }
        public DateTime hkd { get; set; }
        public DateTime huf { get; set; }
        public DateTime idr { get; set; }
        public DateTime ils { get; set; }
        public DateTime inr { get; set; }
        public DateTime jpy { get; set; }
        public DateTime krw { get; set; }
        public DateTime kwd { get; set; }
        public DateTime lkr { get; set; }
        public DateTime ltc { get; set; }
        public DateTime mmk { get; set; }
        public DateTime mxn { get; set; }
        public DateTime myr { get; set; }
        public DateTime ngn { get; set; }
        public DateTime nok { get; set; }
        public DateTime nzd { get; set; }
        public DateTime php { get; set; }
        public DateTime pkr { get; set; }
        public DateTime pln { get; set; }
        public DateTime rub { get; set; }
        public DateTime sar { get; set; }
        public DateTime sek { get; set; }
        public DateTime sgd { get; set; }
        public DateTime thb { get; set; }
        public DateTime _try { get; set; }
        public DateTime twd { get; set; }
        public DateTime uah { get; set; }
        public DateTime usd { get; set; }
        public DateTime vef { get; set; }
        public DateTime vnd { get; set; }
        public DateTime xag { get; set; }
        public DateTime xau { get; set; }
        public DateTime xdr { get; set; }
        public DateTime xlm { get; set; }
        public DateTime xrp { get; set; }
        public DateTime yfi { get; set; }
        public DateTime zar { get; set; }
        public DateTime bits { get; set; }
        public DateTime link { get; set; }
        public DateTime sats { get; set; }
    }

    public class Atl
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Atl_Change_Percentage
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Atl_Date
    {
        public DateTime aed { get; set; }
        public DateTime ars { get; set; }
        public DateTime aud { get; set; }
        public DateTime bch { get; set; }
        public DateTime bdt { get; set; }
        public DateTime bhd { get; set; }
        public DateTime bmd { get; set; }
        public DateTime bnb { get; set; }
        public DateTime brl { get; set; }
        public DateTime btc { get; set; }
        public DateTime cad { get; set; }
        public DateTime chf { get; set; }
        public DateTime clp { get; set; }
        public DateTime cny { get; set; }
        public DateTime czk { get; set; }
        public DateTime dkk { get; set; }
        public DateTime dot { get; set; }
        public DateTime eos { get; set; }
        public DateTime eth { get; set; }
        public DateTime eur { get; set; }
        public DateTime gbp { get; set; }
        public DateTime hkd { get; set; }
        public DateTime huf { get; set; }
        public DateTime idr { get; set; }
        public DateTime ils { get; set; }
        public DateTime inr { get; set; }
        public DateTime jpy { get; set; }
        public DateTime krw { get; set; }
        public DateTime kwd { get; set; }
        public DateTime lkr { get; set; }
        public DateTime ltc { get; set; }
        public DateTime mmk { get; set; }
        public DateTime mxn { get; set; }
        public DateTime myr { get; set; }
        public DateTime ngn { get; set; }
        public DateTime nok { get; set; }
        public DateTime nzd { get; set; }
        public DateTime php { get; set; }
        public DateTime pkr { get; set; }
        public DateTime pln { get; set; }
        public DateTime rub { get; set; }
        public DateTime sar { get; set; }
        public DateTime sek { get; set; }
        public DateTime sgd { get; set; }
        public DateTime thb { get; set; }
        public DateTime _try { get; set; }
        public DateTime twd { get; set; }
        public DateTime uah { get; set; }
        public DateTime usd { get; set; }
        public DateTime vef { get; set; }
        public DateTime vnd { get; set; }
        public DateTime xag { get; set; }
        public DateTime xau { get; set; }
        public DateTime xdr { get; set; }
        public DateTime xlm { get; set; }
        public DateTime xrp { get; set; }
        public DateTime yfi { get; set; }
        public DateTime zar { get; set; }
        public DateTime bits { get; set; }
        public DateTime link { get; set; }
        public DateTime sats { get; set; }
    }

    public class Market_Cap
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Fully_Diluted_Valuation
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Total_Volume
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class High_24H
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Low_24H
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Price_Change_24H_In_Currency
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Price_Change_Percentage_1H_In_Currency
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Price_Change_Percentage_24H_In_Currency
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Price_Change_Percentage_7D_In_Currency
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Price_Change_Percentage_14D_In_Currency
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Price_Change_Percentage_30D_In_Currency
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Price_Change_Percentage_60D_In_Currency
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Price_Change_Percentage_200D_In_Currency
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Price_Change_Percentage_1Y_In_Currency
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Market_Cap_Change_24H_In_Currency
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Market_Cap_Change_Percentage_24H_In_Currency
    {
        public string aed { get; set; }
        public string ars { get; set; }
        public string aud { get; set; }
        public string bch { get; set; }
        public string bdt { get; set; }
        public string bhd { get; set; }
        public string bmd { get; set; }
        public string bnb { get; set; }
        public string brl { get; set; }
        public string btc { get; set; }
        public string cad { get; set; }
        public string chf { get; set; }
        public string clp { get; set; }
        public string cny { get; set; }
        public string czk { get; set; }
        public string dkk { get; set; }
        public string dot { get; set; }
        public string eos { get; set; }
        public string eth { get; set; }
        public string eur { get; set; }
        public string gbp { get; set; }
        public string hkd { get; set; }
        public string huf { get; set; }
        public string idr { get; set; }
        public string ils { get; set; }
        public string inr { get; set; }
        public string jpy { get; set; }
        public string krw { get; set; }
        public string kwd { get; set; }
        public string lkr { get; set; }
        public string ltc { get; set; }
        public string mmk { get; set; }
        public string mxn { get; set; }
        public string myr { get; set; }
        public string ngn { get; set; }
        public string nok { get; set; }
        public string nzd { get; set; }
        public string php { get; set; }
        public string pkr { get; set; }
        public string pln { get; set; }
        public string rub { get; set; }
        public string sar { get; set; }
        public string sek { get; set; }
        public string sgd { get; set; }
        public string thb { get; set; }
        public string _try { get; set; }
        public string twd { get; set; }
        public string uah { get; set; }
        public string usd { get; set; }
        public string vef { get; set; }
        public string vnd { get; set; }
        public string xag { get; set; }
        public string xau { get; set; }
        public string xdr { get; set; }
        public string xlm { get; set; }
        public string xrp { get; set; }
        public string yfi { get; set; }
        public string zar { get; set; }
        public string bits { get; set; }
        public string link { get; set; }
        public string sats { get; set; }
    }

    public class Community_Data
    {
        public object facebook_likes { get; set; }
        public string twitter_followers { get; set; }
        public string reddit_average_posts_48h { get; set; }
        public string reddit_average_comments_48h { get; set; }
        public string reddit_subscribers { get; set; }
        public string reddit_accounts_active_48h { get; set; }
        public object telegram_channel_user_count { get; set; }
    }

    public class Developer_Data
    {
        public string forks { get; set; }
        public string stars { get; set; }
        public string subscribers { get; set; }
        public string total_issues { get; set; }
        public string closed_issues { get; set; }
        public string pull_requests_merged { get; set; }
        public string pull_request_contributors { get; set; }
        public Code_Additions_Deletions_4_Weeks code_additions_deletions_4_weeks { get; set; }
        public string commit_count_4_weeks { get; set; }
        public string[] last_4_weeks_commit_activity_series { get; set; }
    }

    public class Code_Additions_Deletions_4_Weeks
    {
        public string additions { get; set; }
        public string deletions { get; set; }
    }

    public class Public_stringerest_Stats
    {
        public string alexa_rank { get; set; }
        public object bing_matches { get; set; }
    }

    public class Ticker
    {
        public string _base { get; set; }
        public string target { get; set; }
        public Market market { get; set; }
        public string last { get; set; }
        public string volume { get; set; }
        public Converted_Last converted_last { get; set; }
        public Converted_Volume converted_volume { get; set; }
        public string trust_score { get; set; }
        public string bid_ask_spread_percentage { get; set; }
        public DateTime timestamp { get; set; }
        public DateTime last_traded_at { get; set; }
        public DateTime last_fetch_at { get; set; }
        public bool is_anomaly { get; set; }
        public bool is_stale { get; set; }
        public string trade_url { get; set; }
        public object token_info_url { get; set; }
        public string coin_id { get; set; }
        public string target_coin_id { get; set; }
    }

    public class Market
    {
        public string name { get; set; }
        public string identifier { get; set; }
        public bool has_trading_incentive { get; set; }
    }

    public class Converted_Last
    {
        public string btc { get; set; }
        public string eth { get; set; }
        public string usd { get; set; }
    }

    public class Converted_Volume
    {
        public string btc { get; set; }
        public string eth { get; set; }
        public string usd { get; set; }
    }
}
